routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;

// Admin Custom Routes

Route::get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

// Dashboard Controller
Route::namespace(Admin::class)
    ->controller(DashboardController::class)
    ->prefix('dashboard')->name('dashboard.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
    });

// Database Backup Controller
Route::namespace(Admin::class)
    ->controller(DatabaseBackupController::class)
    ->prefix('database')->name('database.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('backup', 'backup')->name('backup');
        Route::get('download-file/{filename}', 'downloadFile')->name('download-file');
        Route::get('create-new-backup', 'createNewBackup')->name('create-new-backup');
        Route::get('create-new-main-backup', 'createNewMainBackup')->name('create-new-main-backup');
    });

// Quotes Controller
Route::namespace(Admin::class)
    ->controller(QuotesController::class)
    ->prefix('quotes')->name('quotes.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::post('add', 'add')->name('add');
        Route::match(['post', 'get'],'edit/{id}', 'edit')->name('edit');
        Route::delete('delete/{id}', 'delete')->name('delete');
        Route::get('get-all-quotes', 'getAllQuotes')->name('get-all-quotes');
        Route::get('is-active/{id}/{process}', 'isActive')->name('is-active');
    });

// Holidays Controller
Route::namespace(Admin::class)
    ->controller(HolidaysController::class)
    ->prefix('holidays')->name('holidays.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::get('get-all-holidays', 'getAllHolidays')->name('get-all-holidays');
        Route::post('add', 'add')->name('add');
        Route::match(['post', 'get'], 'edit/{id}', 'edit')->name('edit');
        Route::delete('delete/{id}', 'delete')->name('delete');
    });

// Users Controller
Route::namespace(Admin::class)
    ->controller(UsersController::class)
    ->prefix('users')->name('users.')
    ->middleware(['auth', 'role:admin'])->group(function(){
        Route::match(['post', 'get'],'add', 'add')->name('add');
        Route::match(['post', 'get'],'edit', 'edit')->name('edit');
        Route::get('admin', 'admin')->name('admin');
        Route::get('manager', 'manager')->name('manager');
        Route::get('index', 'index')->name('index');
        Route::get('account-setting', 'accountSetting')->name('account-setting');
        Route::get('is-active/{id}/{process}', 'isActive')->name('is-active');
    });

// EmployeeRoles Controller
Route::namespace(Admin::class)
    ->controller(EmployeeRolesController::class)
    ->prefix('employee-roles')->name('employee-roles.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::post('add', 'add')->name('add');
        Route::match(['post', 'get'], 'edit/{id}', 'edit')->name('edit');
        Route::delete('delete/{id}/{password}', 'delete')->name('delete');
    });

// Employees Controller
Route::namespace(Admin::class)
    ->controller(EmployeesController::class)
    ->prefix('employees')->name('employees.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::post('add', 'add')->name('add');
        Route::match(['post', 'get'], 'edit/{id}', 'edit')->name('edit');
        Route::get('get-birthdays','getBirthdays')->name('get-birthdays');
        Route::get('update-contributions/{userId}','updateContributions')->name('update-contributions');
    });

// Attendances Controller
Route::namespace(Admin::class)
    ->controller(AttendancesController::class)
    ->prefix('attendances')->name('attendances.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::get('today-overtime-attendances', 'todayOvertimeAttendances')->name('today-overtime-attendances');
        Route::get('get-today-overtime-attendances','getTodayOvertimeAttendances')->name('get-today-overtime-attendances');
        Route::get('get-attendances','getAttendances')->name('get-attendances');
        Route::get('accomplishment/{id}','accomplishment')->name('accomplishment');
        Route::get('reason/{id}','reason')->name('reason');
        Route::get('update-overtime/{id}','updateOvertime')->name('update-overtime');
        Route::get('home-attendances','homeAttendances')->name('home-attendances');
        Route::get('update-attendance/{id}','updateAttendance')->name('update-attendance');
    });

// Company Settings Controller Controller
Route::namespace(Admin::class)
    ->controller(CompanySettings::class)
    ->prefix('company-settings')->name('company-settings.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::get('get-company-settings','getCompanySettings')->name('get-company-settings');
        Route::post('add','add')->name('add');
        Route::match(['post','get'],'edit/{id}','edit')->name('edit');
        Route::delete('delete/{id}','delete')->name('delete');
        Route::post('active/{id}','active')->name('active');
    });
    
// Contributions Controller Controller
Route::namespace(Admin::class)
    ->controller(ContributionsController::class)
    ->prefix('contributions')->name('contributions.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index', 'index')->name('index');
        Route::match(['post','get'], 'add', 'add')->name('add');
        Route::match(['post','get'], 'edit/{id}', 'edit')->name('edit');
        Route::delete('delete/{id}', 'delete')->name('delete');
    });

// Salary Loans Controller Controller
Route::namespace(Admin::class)
    ->controller(SalaryLoansController::class)
    ->prefix('salary-loans')->name('salary-loans.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index','index')->name('index');
        Route::get('get-salary-loans','getSalaryLoans')->name('get-salary-loans');
        Route::match(['post','get'],'edit/{id}','edit')->name('edit');
        Route::post('status/{id}/{index}','status')->name('status');
    });

// Payroll Controller Controller
Route::namespace(Admin::class)
    ->controller(PayrollsController::class)
    ->prefix('payrolls')->name('payrolls.')
    ->middleware(['auth', 'role:admin'])->group(function () {
        Route::get('index','index')->name('index');
        Route::get('get-attendances/{month?}/{year?}','getAttendances')->name('get-attendances');
        Route::get('get-attendance-lists/{userId}/{month?}/{year?}','getAttendanceLists')->name('getAttendanceLists');
        Route::get('get-estimated-salary/{userId}/{month?}/{year?}', 'getEstimatedSalary')->name('get-estimated-salary');
        Route::get('get-contribution-rate/{userId}/{month?}/{year?}', 'getContributionRate')->name('get-contribution-rate');
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('auth.user.index');
});

// Route::group(['namespace' => 'Auth', 'controller' => 'AuthController', 'prefix' => 'auth', 'as' => 'auth.'], function () {
//     Route::get('index', 'index')->name('index');
// });

// Route::controller(AuthController::class)->prefix('auth')->name('auth.')->group(function () {
//     Route::get('index', 'index')->name('index');
//     Route::post('authenticate', 'authenticate')->name('authenticate');
//     Route::get('logout', 'logout')->name('logout');
// });

// AuthController
Route::prefix('auth')->name('auth.')->group(function () {
    Route::namespace(Auth::class)->controller(AuthController::class)->prefix('user')->name('user.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware(['guest']);
        Route::get('index', 'index')->name('index')->middleware(['guest']);
        Route::post('authenticate', 'authenticate')->name('authenticate')->middleware(['guest']);
        Route::match(['post', 'get'], 'forgot-password', 'forgotPassword')->name('forgot-password')->middleware(['guest']);
        Route::match(['post', 'get'],'password-reset/{token}', 'passwordReset')->name('password-reset')->middleware(['guest']);
        Route::get('logout', 'logout')->name('logout');
    });
});

resources/views/Admin/element/aside.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="index3.html" class="brand-link">
        <img src="{{ asset('logo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
        style="opacity: .8">
        <span class="brand-text font-weight-light">{{ ucwords(__('BNJ-AMS')) }}</span>
    </a>

    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ (auth()->user()->image == null) ? asset('preview.png'):asset('storage/avatars/'.auth()->user()->image) }}" class="img-circle elevation-2" alt="User Image" style="height: 2.1rem; width: 2.1rem;">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ ucfirst(__('Admin')) }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
            data-accordion="false">
                <li class="nav-header">{{ strtoupper(__('generals')) }}</li>
                <li class="nav-item">
                    <a href="{{ route('admin.dashboard.index') }}" class="nav-link {{ (url()->current() == route('admin.dashboard.index')) ? "active":"" }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            {{ ucfirst(__('Dashboard')) }}
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('admin.employees.index') }}" class="nav-link {{url()->current() == route('admin.employees.index') ? 'active': ''}}">
                        <i class="nav-icon fas fa-user-tie"></i>
                        <p>
                            {{ ucfirst(__('Employees')) }}
                        </p>
                    </a>
                </li>

                <li class="nav-item {{ (
                        in_array(url()->current(),[
                           route('admin.attendances.index'),
                           route('admin.attendances.today-overtime-attendances'),
                           route('admin.attendances.home-attendances'),
                       ])
                       ) ? 'menu-is-opening menu-open':'' }}">
                    <a href="#" class="nav-link {{ (
                        in_array(url()->current(),[
                           route('admin.attendances.index'),
                           route('admin.attendances.today-overtime-attendances'),
                           route('admin.attendances.home-attendances'),
                       ])
                       ) ? 'active':'' }}">
                        <i class="nav-icon fas fa-clock"></i>
                        <p>
                            {{ ucfirst(__('Attendance')) }}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.attendances.index') }}" class="nav-link {{ (url()->current() == route('admin.attendances.index')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Attendances')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.attendances.today-overtime-attendances') }}" class="nav-link {{ (url()->current() == route('admin.attendances.today-overtime-attendances')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('OT Attendances')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.attendances.home-attendances') }}" class="nav-link {{ (url()->current() == route('admin.attendances.home-attendances')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Work From Home')) }}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.salary-loans.index') }}" class="nav-link {{route('admin.salary-loans.index') == url()->current()? 'active': ''}}">
                        <i class="nav-icon fas fa-hand-holding-usd"></i>
                        <p>
                            {{ ucfirst(__('Loan')) }}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.payrolls.index') }}" class="nav-link {{route('admin.payrolls.index') == url()->current()? 'active': ''}}">
                        <i class="nav-icon fas fa-money-check-alt"></i>
                        <p>
                            {{ ucfirst(__('Payroll')) }}
                        </p>
                    </a>
                </li>
                <li class="nav-header">{{ strtoupper(__('Settings')) }}</li>
                <li class="nav-item">
                    <a href="{{ route('admin.users.index') }}" class="nav-link {{url()->current() == route('admin.users.index') ? 'active': ''}}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            {{ ucfirst(__('Users')) }}
                        </p>
                    </a>
                </li>

                <li class="nav-item {{ (
                        in_array(url()->current(),[
                           route('admin.employee-roles.index'),
                           route('admin.holidays.index'),
                           route('admin.quotes.index'),
                           route('admin.company-settings.index'),
                           route('admin.contributions.index'),
                       ])
                       ) ? 'menu-is-opening menu-open':'' }}">
                    <a href="#" class="nav-link {{ (
                        in_array(url()->current(),[
                           route('admin.employee-roles.index'),
                           route('admin.holidays.index'),
                           route('admin.quotes.index'),
                           route('admin.company-settings.index'),
                           route('admin.contributions.index'),
                       ])
                       ) ? 'active':'' }}">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            {{ ucfirst(__('System Settings')) }}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.contributions.index') }}" class="nav-link {{ (url()->current() == route('admin.contributions.index')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Contributions')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.holidays.index') }}" class="nav-link {{ (url()->current() == route('admin.holidays.index')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Holidays')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.quotes.index') }}" class="nav-link {{ (url()->current() == route('admin.quotes.index')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Quotes')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.company-settings.index')}}" class="nav-link {{url()->current() == route('admin.company-settings.index')? 'active': ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Attendance Settings')) }}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.employee-roles.index') }}" class="nav-link {{ (url()->current() == route('admin.employee-roles.index')) ? 'active':'' }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ ucfirst(__('Employee Roles')) }}</p>
                            </a>
                        </li>                
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.database.backup') }}" class="nav-link {{ (url()->current() == route('admin.database.backup')) ? "active":"" }}">
                        <i class="nav-icon fas fa-database"></i>
                        <p>
                            {{ ucfirst(__('Database Backups')) }}
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

resources/views/Admin/element/breadcrumb.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">{{ $title_array[1] }}</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    @foreach ($title_array as $item)
                        <li class="breadcrumb-item"><a href="#">{{ $item }}</a></li>
                    @endforeach
                </ol>
            </div>
        </div>
    </div>
</div>

resources/views/Admin/element/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2023 <a href="https://www.facebook.com/bnj.ph/">Brain Network Japan</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0.0.
    </div>
</footer>

resources/views/Admin/element/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="javascript:void(0)" id="clock" style="font-weight: bolder;" class="nav-link active">
                <script>
                    var date = moment().format('H:mm:ss A');
                    document.write(date);

                    $(function () {
                        'use strict';
                        setInterval(function () {
                            $('#clock').text(moment().format('H:mm:ss A'));
                        },1000);
                    });

                </script>
            </a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user"></i>
                {{ auth()->user()->username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Account Settings</span>
                <a href="{{ route('admin.users.account-setting') }}" class="dropdown-item {{ (url()->current() == route('admin.users.account-setting')) ? 'active':'' }}">
                    <i class="fas fa-user mr-2"></i> {{ ucfirst(__('My Account')) }}
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('auth.user.logout') }}" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i> {{ ucfirst(__('Logout')) }}
                </a>
                <div class="dropdown-divider"></div>
            </div>
        </li>
    </ul>
</nav>

resources/views/Admin/element/preloader.blade.php
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('logo.png') }}" alt="AdminLTELogo" height="60" width="60" style="border-radius: 50%;" >
</div>